### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by rmtkable** [BenjaminMcQueen/Portfolio#1]
I would like to see a different color for the names of your education history.  They are a little hard to read against the purple.

Adding in the madlibs project would be awesome.

I would take out the reference to a Start Bootstrap template.

**Comment by BenjaminMcQueen** [comment]
I've taken your complaints into account, and have decided...

...That you're stinky and dumb, hahahahahahaha!

Kidding. All issues addressed. :)
